RSA v2:
  title: RSAdmin
  description: |
   Bob's dev team has spun up an alpha version of a public key database! Can you verify as an administrator?
  category: crypto-web
  flag: FLAG{RSA_G3EE_CE3E_DEE3_RSA}
  points: 200
  port: 8000
  serve: true
  hint: "The only hints you get are in the information section."
