version: '3'

services:
  chain:
    build: ./chain
    image: chain
    ports:
     - "8545:8545"
  deploy:
    build: ./deploy
    image: deploy
    network_mode: "host"
    depends_on:
     - chain
